http:
    middlewares:

        basic-auth:
            basicAuth:
                usersFile: "/auth/.htpasswd"
                realm: "Traefik 2 Basic Auth"

        rate-limit:
            rateLimit:
                average: 100
                burst: 50

        https-redirect:
            redirectScheme:
                scheme: https
                permanent: true

        secure-headers:
            headers:
                accessControlAllowMethods:
                    - GET
                    - OPTIONS
                    - PUT
                accessControlMaxAge: 100
                hostsProxyHeaders:
                    - "X-Forwarded-Host"
                stsSeconds: 63072000
                stsIncludeSubdomains: true
                stsPreload: true
                forceSTSHeader: true
                customFrameOptionsValue: SAMEORIGIN
                contentTypeNosniff: true
                referrerPolicy: "same-origin"
                permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
                customResponseHeaders:
                    X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
                    server: ""

        oauth:
            forwardAuth:
                address: "http://oauth.local:4181"
                trustForwardHeader: true
                authResponseHeaders:
                    - "X-Forwarded-User"

        traefik-bouncer:
            forwardAuth:
                address: "http://traefik-bouncer.local:8080/api/v1/forwardAuth"
                trustForwardedHeader: true

        oauth-external:
            forwardAuth:
                address: "http://oauth.{{env "DOMAIN"}}"
                trustForwardedHeader: true
                authResponseHeaders:
                    - "X-Forwarded-User"

        compress:
            compress: {}

        buffering:
            buffering:
                maxResponseBodyBytes: 2000000
                maxRequestBodyBytes: 10485760
                memRequestBodyBytes: 2097152
                memResponseBodyBytes: 2097152
                retryExpression: "IsNetworkError() && Attempts() <= 2"
